version: '3'

services:
  nginx:
    container_name: project-nginx
    build: docker/nginx
    working_dir: /var/www/app
    ports:
      - "9969:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default-compose.conf:/etc/nginx/conf.d/default-compose.conf
    networks:
      - project-network

  php:
    container_name: project-fpm
    build: docker/php
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    networks:
      - project-network

  mysql:
    container_name: project-mysql
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d/init.sql
    networks:
      - project-network

  phpmyadmin:
    container_name: project-phpmyadmin
    build: docker/phpmyadmin
    restart: on-failure
    ports:
      - "7999:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/phpmyadmin/upload.ini:/usr/local/etc/php/php.ini
    networks:
      - project-network

  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    ports:
      - "2122:80"
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        anonymous
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config
  ###< symfony/mercure-bundle ###

volumes:
    ###> symfony/mercure-bundle ###
    mercure_data:
    mercure_config:
  ###< symfony/mercure-bundle ###

networks:
  project-network:
